/*
 * telemetry_bus.h
 *
 *  Created on: 12 Feb 2020
 *      Author: Arion
 */

#ifndef APPLICATION_HOSTBOARD_INC_COMMUNICATION_TELEMETRY_BUS_H_
#define APPLICATION_HOSTBOARD_INC_COMMUNICATION_TELEMETRY_BUS_H_


#endif /* APPLICATION_HOSTBOARD_INC_COMMUNICATION_TELEMETRY_BUS_H_ */
