/* telemetry_protocol.h
 *
 *  Created on: 19 Apr 2018
 *      Author: Cl�ment Nussbaumer
 */

#ifndef TELEMETRY_TELEMETRY_PROTOCOL_H_
#define TELEMETRY_TELEMETRY_PROTOCOL_H_

enum DatagramPayloadType {
    GPS = 0x01, STATUS = 0x02, TELEMETRY = 0X03, DEBUG = 0X04, MOTOR = 0X05, AIRBRAKES = 0x06
};


#define HEADER_PREAMBLE_FLAG 0x55
#define CONTROL_FLAG 0xFF

// Packet Header size in bytes
#define XBEE_OPTIONS_SIZE 14
#define PAYLOAD_ID_SIZE 1
#define PREFIXE_EPFL_SIZE 4
#define TIMESTAMP_SIZE 4
#define HEADER_SIZE (XBEE_OPTIONS_SIZE + PAYLOAD_ID_SIZE + PREFIXE_EPFL_SIZE + TIMESTAMP_SIZE)

// Sections sizes in bytes
/*
#define PREAMBLE_SIZE 4
#define CONTROL_FLAG_SIZE 1
#define CHECKSUM_SIZE 1
*/
#define TOTAL_DATAGRAM_OVERHEAD (HEADER_SIZE /*+ PREAMBLE_SIZE + CONTROL_FLAG_SIZE + CHECKSUM_SIZE*/)

#define SENSOR_DATAGRAM_PAYLOAD_SIZE 40
#define GPS_DATAGRAM_PAYLOAD_SIZE 17
#define TELEMETRY_RAW_DATAGRAM_PAYLOAD_SIZE 24
#define TELEMETRY_FILTERED_DATAGRAM_PAYLOAD_SIZE 24
#define WARNING_DATAGRAM_PAYLOAD_SIZE 6
#define MOTORPRESSURE_DATAGRAM_PAYLOAD_SIZE 4
#define AB_DATAGRAM_PAYLOAD_SIZE 4
//#define EVENT_DATAGRAM_PAYLOAD_SIZE 6

#endif /* TELEMETRY_TELEMETRY_PROTOCOL_H_ */
