/*
 * events.h
 *
 *  Created on: 12 Feb 2020
 *      Author: Arion
 */

#ifndef APPLICATION_HOSTBOARD_INC_COMMUNICATION_PROTOCOL_PROTOCOL_H_
#define APPLICATION_HOSTBOARD_INC_COMMUNICATION_PROTOCOL_PROTOCOL_H_

#include "test_protocol.h"

#endif /* APPLICATION_HOSTBOARD_INC_COMMUNICATION_PROTOCOL_PROTOCOL_H_ */
